menu:
- {name: 'Projects', url: '/projects'}
- {name: 'Publications', url: '/publications'}
- {name: 'Blog', url: '/blog'}
- {name: 'CV', url: '/cv'}
- {name: 'Gallery', url: '/gallery'}

#projects:

blog:

social:
- {icon: 'github', link: 'https://github.com/Duggireddy-Reddy-Prasanna'}
- {icon: 'twitter', link: 'https://x.com/prasann50548362'}
- {icon: 'instagram', link: 'https://www.instagram.com/reddy_drp/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/reddy-prasanna-duggireddy-19a9721aa/'}
